### ISSUE TITLE
Conflict between strict types and PHP 8

### ISSUE THREAD

**Issue by kalebb4f6** [mll-lab/graphql-php-scalars#19]
I saw your update and there are issues with it relating to strict types and PHP 8, it is necessary to be explicit with every variable and function return in this situation.
I made the necessary adjustments to this issue locally, if I'm given the permission I'll release the pull request with the necessary fix.
[Commit fork](https://github.com/mll-lab/graphql-php-scalars/compare/master...kalebb4f6:graphql-php-scalars:conflict-strict-type)
## Project setup
 - php 8.0.19
 - laravel 9 
 - docker image php:8.0.19-fpm-alpine
## Problems
Fatal error</b>: Type of MLL\GraphQLScalars\JSON::$description must be ?string (as in class
GraphQL\Type\Definition\ScalarType) in <b>/var/www/html/vendor/mll-lab/graphql-php-scalars/src/JSON.php

**Comment by andrew-demb** [comment]
Do you have `webonyx/graphql-php:14.11.7`  installed?

They are broke BC with a patch version bump `v14.11.7`
See also: https://github.com/webonyx/graphql-php/issues/1221

**Comment by kalebb4f6** [comment]
yes 
![image](https://user-images.githubusercontent.com/76947854/191538056-953e8aa4-2520-4e72-91d4-03672933de94.png)

**Comment by kalebb4f6** [comment]
This is simply declaring the types, nothing more, just upload this shit and it works

**Comment by andrew-demb** [comment]
This error triggered due to BC break from upstream library and changes will be reverted afterwards.
So I recommend just to add conflict rule with problem version (like in https://github.com/craftcms/cms/commit/7f1bb95645ba49d415c5e27bb0c9e9865d2f6e85#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34)

---

> This is simply declaring the types, nothing more, just upload this shit and it works

It is (can be considered) a BC break to code that extend changed scalar classes without added the same types onto.
Also, Fatal error about incompatible type just one case from all possible with applied changed in broken version of `webonyx/graphql-php`, so there is no guarantee that patch will help to be fully compatible with that version (`14.11.7`)

**Comment by spawnia** [comment]
I fixed the broken `webonyx/graphql-php` release and maintain a forward-compatible branch in https://github.com/mll-lab/graphql-php-scalars/pull/10

**Comment by kalebb4f6** [comment]
Got it, I saw that the correction of the webonyx package has already been made
